@startuml
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title Asignación de salas a profesores
!$AGENT_COLOR = "#FF7700"
!$AGENT_LETTER = "A"

participant "Agente Profesor" as PA <<$AGENT_LETTER, $AGENT_COLOR>>
participant "DirectoryFacilitator : DF" as YP
participant "Agente Sala" as RA <<$AGENT_LETTER, $AGENT_COLOR>>

== FASE DE INICIALIZACIÓN ==

PA -> YP: Registrarse en las páginas amarillas
RA -> YP: Registrarse en las páginas amarillas

== FASE DE NEGOCIACIÓN ==

activate PA
PA -> PA: Revisar si es su turno (por orden)

loop Para cada curso en los cursos de los profesores
    PA -> RA: CFP(nombre asignatura, vacantes)
    note over RA: En esta parte estariamos preguntando\npor la disponibilidad de salas\ny si se puede acomodar el curso.
    activate RA

    group Evaluación de salas
        RA -> RA: Revisar capacidad
        RA -> RA: Revisar disponibilidad de horario
        RA -> RA: Obtener 'satisfacción' según los limites
        RA -> RA: Generar propuesta
    end

    alt ¿Se puede utilizar esa sala?
        RA --> PA: PROPOSE(dia, bloque, codigo, capacidad, satisfaccion)
    else No se puede utilizar esa sala
        RA --> PA: REFUSE
        note over PA: El agente profesor\nrevisará la siguiente sala
    end
    deactivate RA

    note over PA: Esperar 5 segundos\npara recibir propuestas

    alt Propuesta aceptable
        PA -> RA: ACCEPT_PROPOSAL
        activate RA
        RA -> RA: Actualizar el horario de la sala
        RA -> RA: Escribir en los datos de asignacion_salas.json
        RA -> PA: INFORM
        note over PA: Informar al profesor\nque se ha asignado la sala
        deactivate RA
        PA -> PA: Actualizar los horarios para el profesor
    else No hay propuesta aceptable de salas
        PA -> RA: REJECT_PROPOSAL
    end
end

PA -> PA: Guardar datos en memoria

alt Todos los cursos asignados
    PA -> PA: Buscar el siguiente turno para el otro profesor
    PA ->> PA: INFORM(next_order)
    note over PA: El agente profesor pasa al siguiente\ny se elimina, guardandose en otra\nestructura.
end

deactivate PA

@enduml